---
title: "Contents"
---

## Software 
:::{.callout-note}
For the past several decades, the primary languge used in the lab was MATLAB. Starting from 2021, there's been a combined effort to use Julia for new projects in the lab - for it's promised speed and intuitive mathematical-style language syntax. However, Julia being a new language, the ecosystem lacks any equivalent for many of the mature Psychometrics packages available in R. Also, most of PI's previous software are written in MATLAB. Hence, for the time being we use MATLAB, R, and Julia depending on the needs of the project, but the plan is to completely move to Julia in the future. 
:::


### Julia 

- [Getting Started in Julia](/pages/julia-getting-started.qmd)
- [Setting up Julia via `juliaup`](/pages/juliaup-setup.qmd)

### Slides from Julia Office Hours 
 - [Linear Algebra - SVD (10/10/2022)](/pages/CLA/slides/Lec1.qmd) 
 - [Cognitive Modeling Lab Slides](/pages/CNMLabSlides/Lab1/lab1.qmd)

### R

- [List of R Packages used in the Lab](/pages/r-packagelist.qmd) 

## Books 

### Bayesian Inference 
- McElreath, R. (2020). Statistical rethinking: A Bayesian course with examples in R and Stan. Chapman and Hall/CRC.
- Gelman, A., Carlin, J. B., Stern, H. S., & Rubin, D. B. (1995). Bayesian data analysis. Chapman and Hall/CRC.

## Bayesian Networks 
- Almond, R. G., Mislevy, R. J., Steinberg, L. S., Yan, D., & Williamson, D. M. (2015). Bayesian networks in educational assessment. Springer.
- Scutari, M., & Denis, J. B. (2021). Bayesian networks: with examples in R. Chapman and Hall/CRC.
